version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    mem_limit: 512m
    cpus: "1.0"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: training_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
