export type FoodSeedRow = {
  id: string;
  name: string;
  aliases?: string[];
  category: string;
  kcal: number;
  p: number;
  c: number;
  f: number;
  servingLabel?: string;
  servingGrams?: number;
};

export const SYSTEM_FOODS: FoodSeedRow[] = [
  { id: "pechuga-pollo", name: "Pechuga de pollo", aliases: ["pollo", "suprema"], category: "protein", kcal: 165, p: 31, c: 0, f: 3.6, servingLabel: "1 pechuga", servingGrams: 150 },
  { id: "muslo-pollo", name: "Muslo de pollo", aliases: ["pollo muslo"], category: "protein", kcal: 209, p: 26, c: 0, f: 10.9, servingLabel: "1 muslo", servingGrams: 120 },
  { id: "pollo-asado", name: "Pollo asado", aliases: ["pollo"], category: "protein", kcal: 184, p: 27.3, c: 0, f: 7.4, servingLabel: "100 g" },
  { id: "carne-vacuna-magra", name: "Carne vacuna magra", aliases: ["nalga", "peceto", "cuadril"], category: "protein", kcal: 158, p: 26.5, c: 0, f: 5.2, servingLabel: "bife", servingGrams: 150 },
  { id: "vacio", name: "Vacío", aliases: ["asado", "vacio"], category: "protein", kcal: 232, p: 24, c: 0, f: 15, servingLabel: "porción", servingGrams: 150 },
  { id: "entrana", name: "Entraña", aliases: ["asado"], category: "protein", kcal: 224, p: 23, c: 0, f: 14, servingLabel: "porción", servingGrams: 150 },
  { id: "asado", name: "Asado de tira", aliases: ["costilla", "asado"], category: "protein", kcal: 291, p: 22, c: 0, f: 22, servingLabel: "porción", servingGrams: 150 },
  { id: "bife-chorizo", name: "Bife de chorizo", aliases: ["bife"], category: "protein", kcal: 250, p: 26, c: 0, f: 16, servingLabel: "bife", servingGrams: 200 },
  { id: "bondiola", name: "Bondiola", aliases: ["cerdo"], category: "protein", kcal: 242, p: 18, c: 0, f: 18.5, servingLabel: "porción", servingGrams: 120 },
  { id: "lomo-cerdo", name: "Lomo de cerdo", aliases: ["cerdo"], category: "protein", kcal: 143, p: 26, c: 0, f: 3.5, servingLabel: "porción", servingGrams: 120 },
  { id: "jamon-cocido", name: "Jamón cocido", aliases: ["jamon"], category: "protein", kcal: 145, p: 18, c: 1.5, f: 7, servingLabel: "2 fetas", servingGrams: 40 },
  { id: "chorizo", name: "Chorizo", aliases: ["choripan"], category: "protein", kcal: 296, p: 17, c: 2, f: 24, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "morcilla", name: "Morcilla", aliases: ["parrilla"], category: "protein", kcal: 379, p: 14, c: 1, f: 34, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "milanesa-carne", name: "Milanesa de carne", aliases: ["milanesa"], category: "prepared", kcal: 278, p: 18, c: 12, f: 17, servingLabel: "1 unidad", servingGrams: 150 },
  { id: "milanesa-pollo", name: "Milanesa de pollo", aliases: ["suprema milanesa"], category: "prepared", kcal: 252, p: 20, c: 11, f: 14, servingLabel: "1 unidad", servingGrams: 150 },
  { id: "huevo", name: "Huevo", aliases: ["huevos"], category: "protein", kcal: 155, p: 13, c: 1.1, f: 11, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "clara-huevo", name: "Clara de huevo", aliases: ["clara"], category: "protein", kcal: 52, p: 11, c: 0.7, f: 0.2, servingLabel: "1 clara", servingGrams: 33 },
  { id: "yema-huevo", name: "Yema de huevo", aliases: ["yema"], category: "protein", kcal: 322, p: 16, c: 3.6, f: 27, servingLabel: "1 yema", servingGrams: 17 },
  { id: "atun-natural", name: "Atún al natural", aliases: ["atun lata"], category: "protein", kcal: 116, p: 26, c: 0, f: 1, servingLabel: "1 lata", servingGrams: 120 },
  { id: "atun-aceite", name: "Atún en aceite", aliases: ["atun"], category: "protein", kcal: 198, p: 29, c: 0, f: 8, servingLabel: "1 lata", servingGrams: 120 },
  { id: "merluza", name: "Merluza", aliases: ["pescado"], category: "protein", kcal: 86, p: 18.3, c: 0, f: 1.3, servingLabel: "filet", servingGrams: 150 },
  { id: "salmon", name: "Salmón", aliases: ["pescado"], category: "protein", kcal: 208, p: 20, c: 0, f: 13, servingLabel: "filet", servingGrams: 150 },
  { id: "langostinos", name: "Langostinos", aliases: ["camarones"], category: "protein", kcal: 99, p: 24, c: 0.2, f: 0.3, servingLabel: "porción", servingGrams: 120 },
  { id: "calamar", name: "Calamar", aliases: ["rabas"], category: "protein", kcal: 92, p: 16, c: 3, f: 1.4, servingLabel: "porción", servingGrams: 120 },
  { id: "sardinas", name: "Sardinas en lata", aliases: ["sardina"], category: "protein", kcal: 208, p: 25, c: 0, f: 11.5, servingLabel: "1 lata", servingGrams: 90 },
  { id: "whey", name: "Proteína en polvo (whey)", aliases: ["proteina", "whey", "shake"], category: "protein", kcal: 370, p: 80, c: 7, f: 3, servingLabel: "1 scoop", servingGrams: 30 },
  { id: "tofu", name: "Tofu", aliases: ["soja"], category: "protein", kcal: 76, p: 8, c: 1.9, f: 4.8, servingLabel: "porción", servingGrams: 100 },
  { id: "lentejas-cocidas", name: "Lentejas cocidas", aliases: ["lenteja", "guiso"], category: "protein", kcal: 116, p: 9, c: 20, f: 0.4, servingLabel: "1 taza", servingGrams: 180 },
  { id: "garbanzos-cocidos", name: "Garbanzos cocidos", aliases: ["garbanzo"], category: "protein", kcal: 164, p: 8.9, c: 27, f: 2.6, servingLabel: "1 taza", servingGrams: 164 },
  { id: "porotos-cocidos", name: "Porotos cocidos", aliases: ["alubias", "poroto"], category: "protein", kcal: 127, p: 8.7, c: 23, f: 0.5, servingLabel: "1 taza", servingGrams: 170 },
  { id: "soja-texturizada", name: "Soja texturizada hidratada", aliases: ["soja"], category: "protein", kcal: 119, p: 16, c: 9, f: 0.5, servingLabel: "porción", servingGrams: 100 },

  { id: "arroz-blanco", name: "Arroz blanco cocido", aliases: ["arroz"], category: "carb", kcal: 130, p: 2.7, c: 28, f: 0.3, servingLabel: "1 taza", servingGrams: 150 },
  { id: "arroz-integral", name: "Arroz integral cocido", aliases: ["arroz"], category: "carb", kcal: 123, p: 2.7, c: 26, f: 1, servingLabel: "1 taza", servingGrams: 150 },
  { id: "fideos-cocidos", name: "Fideos cocidos", aliases: ["pasta", "spaghetti"], category: "carb", kcal: 158, p: 5.8, c: 31, f: 0.9, servingLabel: "1 plato", servingGrams: 200 },
  { id: "noquis", name: "Ñoquis", aliases: ["ñoqui", "pasta"], category: "carb", kcal: 133, p: 3.8, c: 27, f: 0.5, servingLabel: "1 plato", servingGrams: 200 },
  { id: "ravioles", name: "Ravioles", aliases: ["pasta"], category: "carb", kcal: 203, p: 8, c: 32, f: 4.5, servingLabel: "1 plato", servingGrams: 200 },
  { id: "papa-cocida", name: "Papa cocida", aliases: ["patata"], category: "carb", kcal: 87, p: 1.9, c: 20, f: 0.1, servingLabel: "1 mediana", servingGrams: 150 },
  { id: "papa-frita", name: "Papas fritas", aliases: ["fritas"], category: "carb", kcal: 312, p: 3.4, c: 41, f: 15, servingLabel: "porción", servingGrams: 150 },
  { id: "pure-papa", name: "Puré de papa", aliases: ["pure"], category: "carb", kcal: 89, p: 1.7, c: 13, f: 3.3, servingLabel: "1 taza", servingGrams: 210 },
  { id: "batata", name: "Batata cocida", aliases: ["camote"], category: "carb", kcal: 86, p: 1.6, c: 20, f: 0.1, servingLabel: "1 mediana", servingGrams: 130 },
  { id: "avena", name: "Avena (seca)", aliases: ["avena", "oatmeal"], category: "carb", kcal: 389, p: 17, c: 66, f: 7, servingLabel: "1 taza cruda", servingGrams: 40 },
  { id: "avena-cocida", name: "Avena cocida", aliases: ["porridge"], category: "carb", kcal: 71, p: 2.5, c: 12, f: 1.5, servingLabel: "1 taza", servingGrams: 200 },
  { id: "pan-frances", name: "Pan francés", aliases: ["pan", "flauta"], category: "carb", kcal: 274, p: 9, c: 53, f: 3, servingLabel: "1 unidad", servingGrams: 60 },
  { id: "pan-lactal", name: "Pan lactal", aliases: ["pan de molde"], category: "carb", kcal: 265, p: 8, c: 49, f: 3.3, servingLabel: "1 feta", servingGrams: 25 },
  { id: "pan-integral", name: "Pan integral", aliases: ["pan"], category: "carb", kcal: 247, p: 13, c: 41, f: 4.2, servingLabel: "1 feta", servingGrams: 30 },
  { id: "tostadas", name: "Tostadas de mesa", aliases: ["tostada"], category: "carb", kcal: 392, p: 10, c: 72, f: 6, servingLabel: "2 tostadas", servingGrams: 20 },
  { id: "galletitas-agua", name: "Galletitas de agua", aliases: ["galletitas"], category: "carb", kcal: 432, p: 10, c: 72, f: 11, servingLabel: "6 unidades", servingGrams: 30 },
  { id: "granola", name: "Granola", aliases: ["muesli"], category: "carb", kcal: 471, p: 10, c: 64, f: 20, servingLabel: "1/2 taza", servingGrams: 45 },
  { id: "quinoa-cocida", name: "Quinoa cocida", aliases: ["quinoa"], category: "carb", kcal: 120, p: 4.4, c: 21.3, f: 1.9, servingLabel: "1 taza", servingGrams: 185 },
  { id: "choclo", name: "Choclo", aliases: ["maiz"], category: "carb", kcal: 96, p: 3.4, c: 21, f: 1.5, servingLabel: "1 choclo", servingGrams: 150 },
  { id: "polenta", name: "Polenta cocida", aliases: ["maiz"], category: "carb", kcal: 85, p: 2, c: 18, f: 0.4, servingLabel: "1 taza", servingGrams: 240 },

  { id: "banana", name: "Banana", aliases: ["banano", "plátano"], category: "fruit", kcal: 89, p: 1.1, c: 23, f: 0.3, servingLabel: "1 unidad", servingGrams: 120 },
  { id: "manzana", name: "Manzana", aliases: ["apple"], category: "fruit", kcal: 52, p: 0.3, c: 14, f: 0.2, servingLabel: "1 unidad", servingGrams: 180 },
  { id: "naranja", name: "Naranja", aliases: ["citrico"], category: "fruit", kcal: 47, p: 0.9, c: 12, f: 0.1, servingLabel: "1 unidad", servingGrams: 150 },
  { id: "mandarina", name: "Mandarina", aliases: ["tangerine"], category: "fruit", kcal: 53, p: 0.8, c: 13, f: 0.3, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "frutilla", name: "Frutillas", aliases: ["fresa"], category: "fruit", kcal: 32, p: 0.7, c: 7.7, f: 0.3, servingLabel: "1 taza", servingGrams: 150 },
  { id: "uva", name: "Uvas", aliases: ["uva"], category: "fruit", kcal: 69, p: 0.7, c: 18, f: 0.2, servingLabel: "1 taza", servingGrams: 150 },
  { id: "pera", name: "Pera", aliases: ["pear"], category: "fruit", kcal: 57, p: 0.4, c: 15, f: 0.1, servingLabel: "1 unidad", servingGrams: 180 },
  { id: "kiwi", name: "Kiwi", aliases: ["kiwi"], category: "fruit", kcal: 61, p: 1.1, c: 15, f: 0.5, servingLabel: "1 unidad", servingGrams: 75 },
  { id: "sandia", name: "Sandía", aliases: ["sandia"], category: "fruit", kcal: 30, p: 0.6, c: 8, f: 0.2, servingLabel: "1 rodaja", servingGrams: 200 },
  { id: "melon", name: "Melón", aliases: ["melon"], category: "fruit", kcal: 34, p: 0.8, c: 8, f: 0.2, servingLabel: "1 taza", servingGrams: 160 },
  { id: "arandanos", name: "Arándanos", aliases: ["blueberry"], category: "fruit", kcal: 57, p: 0.7, c: 14, f: 0.3, servingLabel: "1 taza", servingGrams: 140 },
  { id: "durazno", name: "Durazno", aliases: ["melocoton"], category: "fruit", kcal: 39, p: 0.9, c: 10, f: 0.3, servingLabel: "1 unidad", servingGrams: 150 },
  { id: "palta", name: "Palta", aliases: ["aguacate", "avocado"], category: "fat", kcal: 160, p: 2, c: 8.5, f: 15, servingLabel: "1/2 unidad", servingGrams: 70 },

  { id: "brocoli", name: "Brócoli", aliases: ["brocoli"], category: "veg", kcal: 34, p: 2.8, c: 7, f: 0.4, servingLabel: "1 taza", servingGrams: 90 },
  { id: "espinaca", name: "Espinaca", aliases: ["verde"], category: "veg", kcal: 23, p: 2.9, c: 3.6, f: 0.4, servingLabel: "1 taza", servingGrams: 30 },
  { id: "lechuga", name: "Lechuga", aliases: ["ensalada"], category: "veg", kcal: 15, p: 1.4, c: 2.9, f: 0.2, servingLabel: "plato", servingGrams: 80 },
  { id: "tomate", name: "Tomate", aliases: ["tomate"], category: "veg", kcal: 18, p: 0.9, c: 3.9, f: 0.2, servingLabel: "1 unidad", servingGrams: 120 },
  { id: "zanahoria", name: "Zanahoria", aliases: ["zanahoria"], category: "veg", kcal: 41, p: 0.9, c: 10, f: 0.2, servingLabel: "1 unidad", servingGrams: 60 },
  { id: "pepino", name: "Pepino", aliases: ["pepino"], category: "veg", kcal: 15, p: 0.7, c: 3.6, f: 0.1, servingLabel: "1 unidad", servingGrams: 150 },
  { id: "morron", name: "Morrón", aliases: ["pimiento", "aji"], category: "veg", kcal: 31, p: 1, c: 6, f: 0.3, servingLabel: "1 unidad", servingGrams: 120 },
  { id: "cebolla", name: "Cebolla", aliases: ["cebolla"], category: "veg", kcal: 40, p: 1.1, c: 9.3, f: 0.1, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "zapallo", name: "Zapallo", aliases: ["calabaza"], category: "veg", kcal: 26, p: 1, c: 6.5, f: 0.1, servingLabel: "taza", servingGrams: 120 },
  { id: "zucchini", name: "Zucchini", aliases: ["zapallito"], category: "veg", kcal: 17, p: 1.2, c: 3.1, f: 0.3, servingLabel: "1 unidad", servingGrams: 150 },
  { id: "champignon", name: "Champignones", aliases: ["hongo", "mushroom"], category: "veg", kcal: 22, p: 3.1, c: 3.3, f: 0.3, servingLabel: "taza", servingGrams: 70 },
  { id: "coliflor", name: "Coliflor", aliases: ["coliflor"], category: "veg", kcal: 25, p: 1.9, c: 5, f: 0.3, servingLabel: "taza", servingGrams: 100 },
  { id: "repollo", name: "Repollo", aliases: ["col"], category: "veg", kcal: 25, p: 1.3, c: 6, f: 0.1, servingLabel: "taza", servingGrams: 90 },
  { id: "chaucha", name: "Chauchas", aliases: ["ejote"], category: "veg", kcal: 31, p: 1.8, c: 7, f: 0.2, servingLabel: "taza", servingGrams: 100 },
  { id: "berenjena", name: "Berenjena", aliases: ["berenjena"], category: "veg", kcal: 25, p: 1, c: 6, f: 0.2, servingLabel: "1 unidad", servingGrams: 200 },

  { id: "leche-entera", name: "Leche entera", aliases: ["leche"], category: "dairy", kcal: 61, p: 3.2, c: 4.8, f: 3.3, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "leche-descremada", name: "Leche descremada", aliases: ["leche"], category: "dairy", kcal: 34, p: 3.4, c: 5, f: 0.1, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "yogurt-entero", name: "Yogur entero", aliases: ["yogur", "yogurt"], category: "dairy", kcal: 61, p: 3.5, c: 4.7, f: 3.3, servingLabel: "1 pote", servingGrams: 125 },
  { id: "yogurt-descremado", name: "Yogur descremado", aliases: ["yogur"], category: "dairy", kcal: 56, p: 5.7, c: 7.7, f: 0.2, servingLabel: "1 pote", servingGrams: 125 },
  { id: "yogurt-griego", name: "Yogur griego", aliases: ["griego"], category: "dairy", kcal: 97, p: 9, c: 3.6, f: 5, servingLabel: "1 pote", servingGrams: 150 },
  { id: "queso-cremoso", name: "Queso cremoso", aliases: ["queso"], category: "dairy", kcal: 330, p: 18, c: 3, f: 27, servingLabel: "2 fetas", servingGrams: 40 },
  { id: "queso-tybo", name: "Queso tybo", aliases: ["queso sandwich"], category: "dairy", kcal: 357, p: 24, c: 2, f: 28, servingLabel: "2 fetas", servingGrams: 40 },
  { id: "muzzarella", name: "Muzzarella", aliases: ["mozzarella", "muzza"], category: "dairy", kcal: 280, p: 22, c: 2.2, f: 20, servingLabel: "porción", servingGrams: 50 },
  { id: "queso-untable", name: "Queso untable", aliases: ["untar"], category: "dairy", kcal: 250, p: 8, c: 4, f: 22, servingLabel: "1 cda", servingGrams: 20 },
  { id: "ricota", name: "Ricota", aliases: ["ricotta"], category: "dairy", kcal: 174, p: 11, c: 3, f: 13, servingLabel: "4 cdas", servingGrams: 80 },
  { id: "cottage", name: "Cottage", aliases: ["queso cottage"], category: "dairy", kcal: 98, p: 11, c: 3.4, f: 4.3, servingLabel: "1/2 taza", servingGrams: 110 },
  { id: "parmesano", name: "Queso parmesano", aliases: ["reggianito"], category: "dairy", kcal: 431, p: 38, c: 4.1, f: 29, servingLabel: "1 cda", servingGrams: 10 },
  { id: "dulce-leche", name: "Dulce de leche", aliases: ["ddl"], category: "dairy", kcal: 315, p: 6.6, c: 55, f: 7.4, servingLabel: "1 cda", servingGrams: 20 },

  { id: "aceite-oliva", name: "Aceite de oliva", aliases: ["aceite"], category: "fat", kcal: 884, p: 0, c: 0, f: 100, servingLabel: "1 cda", servingGrams: 13 },
  { id: "aceite-girasol", name: "Aceite de girasol", aliases: ["aceite"], category: "fat", kcal: 884, p: 0, c: 0, f: 100, servingLabel: "1 cda", servingGrams: 13 },
  { id: "manteca", name: "Manteca", aliases: ["mantequilla"], category: "fat", kcal: 717, p: 0.9, c: 0.1, f: 81, servingLabel: "1 cda", servingGrams: 10 },
  { id: "manteca-mani", name: "Manteca de maní", aliases: ["peanut butter"], category: "fat", kcal: 588, p: 25, c: 20, f: 50, servingLabel: "1 cda", servingGrams: 16 },
  { id: "mayonesa", name: "Mayonesa", aliases: ["mayo"], category: "fat", kcal: 680, p: 1, c: 0.6, f: 75, servingLabel: "1 cda", servingGrams: 15 },
  { id: "almendras", name: "Almendras", aliases: ["frutos secos"], category: "fat", kcal: 579, p: 21, c: 22, f: 50, servingLabel: "1 puñado", servingGrams: 28 },
  { id: "nueces", name: "Nueces", aliases: ["nuez"], category: "fat", kcal: 654, p: 15, c: 14, f: 65, servingLabel: "1 puñado", servingGrams: 28 },
  { id: "mani", name: "Maní", aliases: ["cacahuate"], category: "fat", kcal: 567, p: 26, c: 16, f: 49, servingLabel: "1 puñado", servingGrams: 28 },
  { id: "castanas", name: "Castañas de cajú", aliases: ["caju", "cashew"], category: "fat", kcal: 553, p: 18, c: 30, f: 44, servingLabel: "1 puñado", servingGrams: 28 },
  { id: "chia", name: "Semillas de chía", aliases: ["chia"], category: "fat", kcal: 486, p: 17, c: 42, f: 31, servingLabel: "1 cda", servingGrams: 12 },
  { id: "linaza", name: "Lino / linaza", aliases: ["flax"], category: "fat", kcal: 534, p: 18, c: 29, f: 42, servingLabel: "1 cda", servingGrams: 10 },
  { id: "aceite-coco", name: "Aceite de coco", aliases: ["coco"], category: "fat", kcal: 862, p: 0, c: 0, f: 100, servingLabel: "1 cda", servingGrams: 13 },
  { id: "aceitunas", name: "Aceitunas", aliases: ["oliva"], category: "fat", kcal: 115, p: 0.8, c: 6, f: 11, servingLabel: "10 unidades", servingGrams: 30 },

  { id: "empanada-carne", name: "Empanada de carne", aliases: ["empanada"], category: "prepared", kcal: 268, p: 9, c: 28, f: 13, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "empanada-jyq", name: "Empanada de jamón y queso", aliases: ["empanada"], category: "prepared", kcal: 275, p: 10, c: 27, f: 14, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "medialuna", name: "Medialuna", aliases: ["croissant", "factura"], category: "prepared", kcal: 406, p: 8, c: 46, f: 21, servingLabel: "1 unidad", servingGrams: 55 },
  { id: "factura", name: "Factura", aliases: ["vigilante", "cañoncito"], category: "prepared", kcal: 420, p: 7, c: 52, f: 20, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "pizza-muzzarella", name: "Pizza muzzarella", aliases: ["pizza"], category: "prepared", kcal: 266, p: 11, c: 33, f: 10, servingLabel: "1 porción", servingGrams: 120 },
  { id: "fainá", name: "Fainá", aliases: ["faina"], category: "prepared", kcal: 220, p: 8, c: 22, f: 11, servingLabel: "1 porción", servingGrams: 80 },
  { id: "tarta-verdura", name: "Tarta de verdura", aliases: ["tarta"], category: "prepared", kcal: 190, p: 6, c: 18, f: 10, servingLabel: "1 porción", servingGrams: 150 },
  { id: "tarta-jyq", name: "Tarta jamón y queso", aliases: ["tarta"], category: "prepared", kcal: 240, p: 12, c: 16, f: 14, servingLabel: "1 porción", servingGrams: 150 },
  { id: "guiso-lentejas", name: "Guiso de lentejas", aliases: ["guiso"], category: "prepared", kcal: 128, p: 7, c: 18, f: 3, servingLabel: "1 plato", servingGrams: 300 },
  { id: "locro", name: "Locro", aliases: ["locro"], category: "prepared", kcal: 145, p: 8, c: 16, f: 5.5, servingLabel: "1 plato", servingGrams: 300 },
  { id: "milanesa-napo", name: "Milanesa napolitana", aliases: ["napo"], category: "prepared", kcal: 245, p: 18, c: 10, f: 15, servingLabel: "1 unidad", servingGrams: 220 },
  { id: "hamburguesa", name: "Hamburguesa de carne", aliases: ["burger"], category: "prepared", kcal: 254, p: 17, c: 0, f: 20, servingLabel: "1 medallón", servingGrams: 100 },
  { id: "pancho", name: "Pancho / hot dog", aliases: ["panchito"], category: "prepared", kcal: 290, p: 10, c: 24, f: 17, servingLabel: "1 unidad", servingGrams: 110 },
  { id: "choripan", name: "Choripán", aliases: ["chori"], category: "prepared", kcal: 295, p: 13, c: 22, f: 17, servingLabel: "1 unidad", servingGrams: 180 },
  { id: "sandwich-jyq", name: "Tostado jamón y queso", aliases: ["tostado", "sandwich"], category: "prepared", kcal: 268, p: 14, c: 24, f: 13, servingLabel: "1 unidad", servingGrams: 140 },
  { id: "ensalada-cesar", name: "Ensalada César", aliases: ["cesar"], category: "prepared", kcal: 170, p: 8, c: 7, f: 13, servingLabel: "1 bowl", servingGrams: 250 },
  { id: "ensalada-completa", name: "Ensalada completa", aliases: ["ensalada"], category: "prepared", kcal: 95, p: 6, c: 8, f: 4, servingLabel: "1 bowl", servingGrams: 250 },
  { id: "sushi-roll", name: "Sushi (roll)", aliases: ["sushi"], category: "prepared", kcal: 150, p: 6, c: 28, f: 2, servingLabel: "8 piezas", servingGrams: 180 },
  { id: "omelette", name: "Omelette 2 huevos", aliases: ["tortilla huevo"], category: "prepared", kcal: 168, p: 12, c: 1, f: 13, servingLabel: "1 unidad", servingGrams: 110 },
  { id: "tortilla-papa", name: "Tortilla de papa", aliases: ["tortilla"], category: "prepared", kcal: 178, p: 7, c: 14, f: 10, servingLabel: "1 porción", servingGrams: 150 },
  { id: "empanada-humita", name: "Empanada de humita", aliases: ["empanada"], category: "prepared", kcal: 240, p: 7, c: 32, f: 10, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "provoleta", name: "Provoleta", aliases: ["provolone"], category: "prepared", kcal: 351, p: 26, c: 2, f: 27, servingLabel: "1 disco", servingGrams: 80 },
  { id: "papas-rusticas", name: "Papas rústicas al horno", aliases: ["papa horno"], category: "prepared", kcal: 149, p: 2.5, c: 24, f: 5, servingLabel: "porción", servingGrams: 180 },

  { id: "alfajor", name: "Alfajor", aliases: ["alfajor"], category: "packaged", kcal: 390, p: 6, c: 58, f: 15, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "chocolate", name: "Chocolate", aliases: ["cacao"], category: "packaged", kcal: 546, p: 7.6, c: 46, f: 31, servingLabel: "4 cuadraditos", servingGrams: 20 },
  { id: "helado", name: "Helado", aliases: ["ice cream"], category: "packaged", kcal: 207, p: 3.5, c: 24, f: 11, servingLabel: "1 bocha", servingGrams: 80 },
  { id: "galletitas-dulces", name: "Galletitas dulces", aliases: ["cookies"], category: "packaged", kcal: 480, p: 6, c: 68, f: 20, servingLabel: "3 unidades", servingGrams: 30 },
  { id: "papas-snack", name: "Papas snack", aliases: ["lays", "chips"], category: "packaged", kcal: 536, p: 7, c: 53, f: 34, servingLabel: "1 paquete chico", servingGrams: 30 },
  { id: "barra-cereal", name: "Barra de cereal", aliases: ["barrita"], category: "packaged", kcal: 420, p: 6, c: 68, f: 14, servingLabel: "1 unidad", servingGrams: 25 },
  { id: "mermelada", name: "Mermelada", aliases: ["dulce"], category: "packaged", kcal: 250, p: 0.4, c: 65, f: 0.1, servingLabel: "1 cda", servingGrams: 20 },
  { id: "miel", name: "Miel", aliases: ["honey"], category: "packaged", kcal: 304, p: 0.3, c: 82, f: 0, servingLabel: "1 cda", servingGrams: 21 },
  { id: "azucar", name: "Azúcar", aliases: ["sugar"], category: "packaged", kcal: 387, p: 0, c: 100, f: 0, servingLabel: "1 cda", servingGrams: 12 },
  { id: "ketchup", name: "Ketchup", aliases: ["catsup"], category: "packaged", kcal: 112, p: 1.3, c: 27, f: 0.1, servingLabel: "1 cda", servingGrams: 17 },
  { id: "mostaza", name: "Mostaza", aliases: ["mustard"], category: "packaged", kcal: 66, p: 4.4, c: 5.8, f: 4, servingLabel: "1 cda", servingGrams: 15 },

  { id: "agua", name: "Agua", aliases: ["agua"], category: "drink", kcal: 0, p: 0, c: 0, f: 0, servingLabel: "1 vaso", servingGrams: 250 },
  { id: "cafe", name: "Café (sin azúcar)", aliases: ["cafe"], category: "drink", kcal: 2, p: 0.1, c: 0, f: 0, servingLabel: "1 taza", servingGrams: 180 },
  { id: "mate", name: "Mate (cebado)", aliases: ["yerba"], category: "drink", kcal: 0, p: 0, c: 0, f: 0, servingLabel: "1 mate", servingGrams: 200 },
  { id: "te", name: "Té", aliases: ["tea"], category: "drink", kcal: 1, p: 0, c: 0.2, f: 0, servingLabel: "1 taza", servingGrams: 200 },
  { id: "gaseosa", name: "Gaseosa cola", aliases: ["coca", "soda"], category: "drink", kcal: 42, p: 0, c: 10.6, f: 0, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "gaseosa-zero", name: "Gaseosa zero", aliases: ["coca zero"], category: "drink", kcal: 1, p: 0, c: 0, f: 0, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "jugo-naranja", name: "Jugo de naranja", aliases: ["jugo"], category: "drink", kcal: 45, p: 0.7, c: 10.4, f: 0.2, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "cerveza", name: "Cerveza", aliases: ["birra"], category: "drink", kcal: 43, p: 0.5, c: 3.6, f: 0, servingLabel: "1 pinta", servingGrams: 330 },
  { id: "vino", name: "Vino", aliases: ["malbec"], category: "drink", kcal: 85, p: 0.1, c: 2.6, f: 0, servingLabel: "1 copa", servingGrams: 150 },
  { id: "fernet-coca", name: "Fernet con Coca", aliases: ["fernet"], category: "drink", kcal: 95, p: 0, c: 12, f: 0, servingLabel: "1 vaso", servingGrams: 250 },

  { id: "tostada-arroz", name: "Tostada de arroz", aliases: ["tostadas de arroz", "rice cake", "galletita de arroz", "tortita de arroz", "galleta de arroz"], category: "carb", kcal: 387, p: 8.2, c: 81.5, f: 2.8, servingLabel: "1 unidad", servingGrams: 9 },
  { id: "tostada-arroz-integral", name: "Tostada de arroz integral", aliases: ["rice cake integral", "galletita arroz integral"], category: "carb", kcal: 370, p: 8, c: 77, f: 3.2, servingLabel: "1 unidad", servingGrams: 10 },
  { id: "galletas-arroz", name: "Galletas de arroz", aliases: ["galletitas de arroz", "crackers arroz"], category: "carb", kcal: 392, p: 7.5, c: 82, f: 3, servingLabel: "4 unidades", servingGrams: 20 },
  { id: "arroz-inflado", name: "Arroz inflado", aliases: ["arroz soplado", "puffed rice"], category: "carb", kcal: 383, p: 7, c: 85, f: 1, servingLabel: "1 taza", servingGrams: 20 },
  { id: "copos-maiz", name: "Copos de maíz", aliases: ["corn flakes", "cereal"], category: "carb", kcal: 357, p: 8, c: 84, f: 0.4, servingLabel: "1 taza", servingGrams: 30 },
  { id: "avena-instantanea", name: "Avena instantánea", aliases: ["avena instant", "quaker"], category: "carb", kcal: 370, p: 13, c: 67, f: 6.5, servingLabel: "1 sobre", servingGrams: 40 },
  { id: "salvado-avena", name: "Salvado de avena", aliases: ["bran", "fibra"], category: "carb", kcal: 246, p: 17, c: 66, f: 7, servingLabel: "3 cdas", servingGrams: 20 },
  { id: "pan-pita", name: "Pan pita", aliases: ["pita", "pan arabe"], category: "carb", kcal: 275, p: 9, c: 56, f: 1.2, servingLabel: "1 unidad", servingGrams: 60 },
  { id: "wrap", name: "Wrap / tortilla de harina", aliases: ["tortilla wrap", "lavash"], category: "carb", kcal: 310, p: 8, c: 50, f: 8, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "wrap-integral", name: "Wrap integral", aliases: ["tortilla integral"], category: "carb", kcal: 290, p: 9, c: 48, f: 6, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "pan-hamburguesa", name: "Pan de hamburguesa", aliases: ["bun"], category: "carb", kcal: 280, p: 9, c: 50, f: 5, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "pan-lactal-light", name: "Pan lactal light", aliases: ["pan light", "pan dieta"], category: "carb", kcal: 220, p: 10, c: 42, f: 1.5, servingLabel: "1 feta", servingGrams: 22 },
  { id: "fideos-integrales", name: "Fideos integrales cocidos", aliases: ["pasta integral"], category: "carb", kcal: 124, p: 5, c: 26, f: 0.8, servingLabel: "1 plato", servingGrams: 200 },
  { id: "fideos-arroz", name: "Fideos de arroz cocidos", aliases: ["noodle arroz"], category: "carb", kcal: 109, p: 0.9, c: 25, f: 0.2, servingLabel: "1 plato", servingGrams: 180 },
  { id: "cuscus", name: "Cuscús cocido", aliases: ["couscous"], category: "carb", kcal: 112, p: 3.8, c: 23, f: 0.2, servingLabel: "1 taza", servingGrams: 160 },
  { id: "burgol", name: "Burgol cocido", aliases: ["trigo burgol", "bulgur"], category: "carb", kcal: 83, p: 3, c: 19, f: 0.2, servingLabel: "1 taza", servingGrams: 140 },
  { id: "arroz-yamani", name: "Arroz yamaní cocido", aliases: ["yamani"], category: "carb", kcal: 111, p: 2.6, c: 23, f: 0.9, servingLabel: "1 taza", servingGrams: 150 },
  { id: "konjac", name: "Fideos shirataki / konjac", aliases: ["konjac", "zero pasta"], category: "carb", kcal: 9, p: 0, c: 3, f: 0, servingLabel: "1 plato", servingGrams: 200 },
  { id: "pancakes", name: "Pancakes", aliases: ["panqueques"], category: "carb", kcal: 227, p: 6, c: 28, f: 10, servingLabel: "2 unidades", servingGrams: 80 },
  { id: "waffles", name: "Waffles", aliases: ["waffle"], category: "carb", kcal: 291, p: 8, c: 33, f: 14, servingLabel: "1 unidad", servingGrams: 75 },
  { id: "bagel", name: "Bagel", aliases: ["bagel"], category: "carb", kcal: 257, p: 10, c: 50, f: 1.7, servingLabel: "1 unidad", servingGrams: 90 },
  { id: "pochoclo", name: "Pochoclo (sin manteca)", aliases: ["popcorn", "pochoclos"], category: "carb", kcal: 387, p: 13, c: 78, f: 5, servingLabel: "2 tazas", servingGrams: 20 },

  { id: "pavo", name: "Pechuga de pavo", aliases: ["pavo", "turkey"], category: "protein", kcal: 135, p: 30, c: 0, f: 1, servingLabel: "porción", servingGrams: 120 },
  { id: "jamon-crudo", name: "Jamón crudo", aliases: ["jamon serrano", "prosciutto"], category: "protein", kcal: 220, p: 26, c: 0.5, f: 13, servingLabel: "3 fetas", servingGrams: 30 },
  { id: "lomo-vacuno", name: "Lomo vacuno", aliases: ["lomo"], category: "protein", kcal: 143, p: 27, c: 0, f: 3.5, servingLabel: "bife", servingGrams: 150 },
  { id: "roast-beef", name: "Roast beef", aliases: ["rosbife"], category: "protein", kcal: 140, p: 26, c: 0, f: 4, servingLabel: "4 fetas", servingGrams: 60 },
  { id: "atun-fresco", name: "Atún fresco a la plancha", aliases: ["atun steak"], category: "protein", kcal: 132, p: 28, c: 0, f: 1.3, servingLabel: "filet", servingGrams: 150 },
  { id: "trucha", name: "Trucha", aliases: ["pescado"], category: "protein", kcal: 148, p: 21, c: 0, f: 6.6, servingLabel: "filet", servingGrams: 150 },
  { id: "pejerrey", name: "Pejerrey", aliases: ["pescado"], category: "protein", kcal: 96, p: 18, c: 0, f: 2.3, servingLabel: "filet", servingGrams: 150 },
  { id: "caballa", name: "Caballa", aliases: ["mackerel"], category: "protein", kcal: 205, p: 19, c: 0, f: 14, servingLabel: "filet", servingGrams: 120 },
  { id: "mejillones", name: "Mejillones", aliases: ["moluscos"], category: "protein", kcal: 86, p: 12, c: 3.7, f: 2.2, servingLabel: "porción", servingGrams: 100 },
  { id: "pulpo", name: "Pulpo", aliases: ["pulpo"], category: "protein", kcal: 82, p: 15, c: 2.2, f: 1, servingLabel: "porción", servingGrams: 120 },
  { id: "edamame", name: "Edamame", aliases: ["soja verde"], category: "protein", kcal: 122, p: 11, c: 10, f: 5, servingLabel: "1 taza", servingGrams: 100 },
  { id: "tempeh", name: "Tempeh", aliases: ["tempeh"], category: "protein", kcal: 193, p: 19, c: 9, f: 11, servingLabel: "porción", servingGrams: 80 },
  { id: "seitan", name: "Seitán", aliases: ["seitan", "gluten"], category: "protein", kcal: 143, p: 25, c: 6, f: 2, servingLabel: "porción", servingGrams: 100 },
  { id: "arvejas", name: "Arvejas cocidas", aliases: ["guisantes", "peas"], category: "protein", kcal: 84, p: 5.4, c: 16, f: 0.4, servingLabel: "1 taza", servingGrams: 160 },
  { id: "porotos-negros", name: "Porotos negros cocidos", aliases: ["black beans"], category: "protein", kcal: 132, p: 8.9, c: 24, f: 0.5, servingLabel: "1 taza", servingGrams: 170 },
  { id: "whey-isolate", name: "Proteína isolate", aliases: ["isolate", "whey isolate"], category: "protein", kcal: 370, p: 90, c: 2, f: 1, servingLabel: "1 scoop", servingGrams: 30 },
  { id: "caseina", name: "Caseína", aliases: ["caseina", "night protein"], category: "protein", kcal: 360, p: 78, c: 8, f: 1.5, servingLabel: "1 scoop", servingGrams: 30 },
  { id: "clara-polvo", name: "Clara en polvo", aliases: ["egg white powder"], category: "protein", kcal: 370, p: 82, c: 4, f: 0, servingLabel: "2 cdas", servingGrams: 20 },
  { id: "huevo-duro", name: "Huevo duro", aliases: ["huevo cocido"], category: "protein", kcal: 155, p: 13, c: 1.1, f: 11, servingLabel: "1 unidad", servingGrams: 50 },
  { id: "alitas-pollo", name: "Alitas de pollo", aliases: ["wings"], category: "protein", kcal: 203, p: 19, c: 0, f: 14, servingLabel: "4 alitas", servingGrams: 120 },
  { id: "pavo-feteado", name: "Pavo feteado", aliases: ["fiambre pavo"], category: "protein", kcal: 104, p: 17, c: 2, f: 3, servingLabel: "4 fetas", servingGrams: 40 },
  { id: "salame", name: "Salame", aliases: ["salamin"], category: "protein", kcal: 378, p: 22, c: 1.5, f: 31, servingLabel: "6 fetas", servingGrams: 30 },
  { id: "panceta", name: "Panceta", aliases: ["bacon"], category: "protein", kcal: 417, p: 13, c: 1.4, f: 40, servingLabel: "2 fetas", servingGrams: 16 },

  { id: "leche-almendra", name: "Leche de almendras", aliases: ["almond milk"], category: "dairy", kcal: 17, p: 0.6, c: 0.6, f: 1.1, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "leche-avena", name: "Leche de avena", aliases: ["oat milk"], category: "dairy", kcal: 47, p: 1, c: 7, f: 1.5, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "leche-soja", name: "Leche de soja", aliases: ["soy milk"], category: "dairy", kcal: 54, p: 3.3, c: 6, f: 1.8, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "kefir", name: "Kéfir", aliases: ["kefir"], category: "dairy", kcal: 64, p: 3.6, c: 4.5, f: 3.5, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "skyr", name: "Skyr / yogur proteico", aliases: ["skyr", "yogurt proteico"], category: "dairy", kcal: 63, p: 11, c: 4, f: 0.2, servingLabel: "1 pote", servingGrams: 150 },
  { id: "queso-light", name: "Queso untable light", aliases: ["untable light"], category: "dairy", kcal: 160, p: 10, c: 5, f: 11, servingLabel: "1 cda", servingGrams: 20 },
  { id: "port-salut", name: "Queso port salut", aliases: ["port salut"], category: "dairy", kcal: 314, p: 21, c: 1, f: 25, servingLabel: "2 fetas", servingGrams: 40 },
  { id: "dambo", name: "Queso dambo", aliases: ["dambo"], category: "dairy", kcal: 340, p: 25, c: 1.5, f: 26, servingLabel: "2 fetas", servingGrams: 40 },
  { id: "feta", name: "Queso feta", aliases: ["feta"], category: "dairy", kcal: 264, p: 14, c: 4, f: 21, servingLabel: "cubos", servingGrams: 40 },
  { id: "crema-leche", name: "Crema de leche", aliases: ["crema"], category: "dairy", kcal: 292, p: 2.1, c: 3, f: 31, servingLabel: "1 cda", servingGrams: 15 },
  { id: "leche-chocolatada", name: "Leche chocolatada", aliases: ["chocolatada"], category: "dairy", kcal: 83, p: 3.2, c: 12, f: 2.3, servingLabel: "1 vaso", servingGrams: 200 },

  { id: "anana", name: "Ananá", aliases: ["piña", "pineapple"], category: "fruit", kcal: 50, p: 0.5, c: 13, f: 0.1, servingLabel: "1 taza", servingGrams: 165 },
  { id: "mango", name: "Mango", aliases: ["mango"], category: "fruit", kcal: 60, p: 0.8, c: 15, f: 0.4, servingLabel: "1 unidad", servingGrams: 200 },
  { id: "pomelo", name: "Pomelo", aliases: ["toronja"], category: "fruit", kcal: 42, p: 0.8, c: 11, f: 0.1, servingLabel: "1/2 unidad", servingGrams: 150 },
  { id: "limon", name: "Limón", aliases: ["lemon"], category: "fruit", kcal: 29, p: 1.1, c: 9, f: 0.3, servingLabel: "1 unidad", servingGrams: 60 },
  { id: "frambuesa", name: "Frambuesas", aliases: ["raspberry"], category: "fruit", kcal: 52, p: 1.2, c: 12, f: 0.7, servingLabel: "1 taza", servingGrams: 120 },
  { id: "ciruela", name: "Ciruela", aliases: ["plum"], category: "fruit", kcal: 46, p: 0.7, c: 11, f: 0.3, servingLabel: "1 unidad", servingGrams: 70 },
  { id: "datiles", name: "Dátiles", aliases: ["dates"], category: "fruit", kcal: 277, p: 1.8, c: 75, f: 0.2, servingLabel: "3 unidades", servingGrams: 24 },
  { id: "pasas", name: "Pasas de uva", aliases: ["raisins"], category: "fruit", kcal: 299, p: 3.1, c: 79, f: 0.5, servingLabel: "1 puñado", servingGrams: 30 },
  { id: "coco-rallado", name: "Coco rallado", aliases: ["coco"], category: "fruit", kcal: 660, p: 7, c: 24, f: 65, servingLabel: "2 cdas", servingGrams: 15 },
  { id: "higo", name: "Higo", aliases: ["higos"], category: "fruit", kcal: 74, p: 0.8, c: 19, f: 0.3, servingLabel: "2 unidades", servingGrams: 80 },
  { id: "cereza", name: "Cerezas", aliases: ["guinda"], category: "fruit", kcal: 63, p: 1.1, c: 16, f: 0.2, servingLabel: "1 taza", servingGrams: 140 },

  { id: "rucula", name: "Rúcula", aliases: ["arugula"], category: "veg", kcal: 25, p: 2.6, c: 3.7, f: 0.7, servingLabel: "plato", servingGrams: 40 },
  { id: "kale", name: "Kale", aliases: ["col rizada"], category: "veg", kcal: 49, p: 4.3, c: 9, f: 0.9, servingLabel: "1 taza", servingGrams: 70 },
  { id: "esparragos", name: "Espárragos", aliases: ["asparagus"], category: "veg", kcal: 20, p: 2.2, c: 3.9, f: 0.1, servingLabel: "6 unidades", servingGrams: 90 },
  { id: "apio", name: "Apio", aliases: ["celery"], category: "veg", kcal: 16, p: 0.7, c: 3, f: 0.2, servingLabel: "2 palitos", servingGrams: 80 },
  { id: "rabanito", name: "Rabanitos", aliases: ["rabano"], category: "veg", kcal: 16, p: 0.7, c: 3.4, f: 0.1, servingLabel: "5 unidades", servingGrams: 50 },
  { id: "palmito", name: "Palmitos", aliases: ["hearts of palm"], category: "veg", kcal: 28, p: 2.5, c: 4.6, f: 0.5, servingLabel: "4 unidades", servingGrams: 80 },
  { id: "mix-vegetales", name: "Mix de vegetales salteados", aliases: ["salteado", "wok"], category: "veg", kcal: 45, p: 2, c: 7, f: 1.5, servingLabel: "1 taza", servingGrams: 150 },
  { id: "calabaza-horno", name: "Calabaza al horno", aliases: ["zapallo horno"], category: "veg", kcal: 45, p: 1, c: 10, f: 0.5, servingLabel: "porción", servingGrams: 150 },

  { id: "hummus", name: "Hummus", aliases: ["homus"], category: "fat", kcal: 166, p: 8, c: 14, f: 10, servingLabel: "2 cdas", servingGrams: 30 },
  { id: "guacamole", name: "Guacamole", aliases: ["guaca"], category: "fat", kcal: 150, p: 2, c: 8, f: 13, servingLabel: "2 cdas", servingGrams: 30 },
  { id: "tahini", name: "Tahini", aliases: ["pasta sesamo"], category: "fat", kcal: 595, p: 17, c: 21, f: 54, servingLabel: "1 cda", servingGrams: 15 },
  { id: "pistacho", name: "Pistachos", aliases: ["pistachio"], category: "fat", kcal: 560, p: 20, c: 28, f: 45, servingLabel: "1 puñado", servingGrams: 28 },
  { id: "avellanas", name: "Avellanas", aliases: ["hazelnut"], category: "fat", kcal: 628, p: 15, c: 17, f: 61, servingLabel: "1 puñado", servingGrams: 28 },
  { id: "semillas-girasol", name: "Semillas de girasol", aliases: ["girasol"], category: "fat", kcal: 584, p: 21, c: 20, f: 51, servingLabel: "2 cdas", servingGrams: 20 },
  { id: "semillas-zapallo", name: "Semillas de zapallo", aliases: ["pepitas"], category: "fat", kcal: 559, p: 30, c: 11, f: 49, servingLabel: "2 cdas", servingGrams: 20 },
  { id: "aceite-sesamo", name: "Aceite de sésamo", aliases: ["sesamo"], category: "fat", kcal: 884, p: 0, c: 0, f: 100, servingLabel: "1 cda", servingGrams: 13 },

  { id: "milanesa-soja", name: "Milanesa de soja", aliases: ["medallón soja"], category: "prepared", kcal: 190, p: 16, c: 12, f: 8, servingLabel: "1 unidad", servingGrams: 100 },
  { id: "hamburguesa-lenteja", name: "Hamburguesa de lentejas", aliases: ["medallon vegetal"], category: "prepared", kcal: 170, p: 9, c: 20, f: 5, servingLabel: "1 medallón", servingGrams: 100 },
  { id: "empanada-pollo", name: "Empanada de pollo", aliases: ["empanada"], category: "prepared", kcal: 250, p: 11, c: 27, f: 11, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "empanada-verdura", name: "Empanada de verdura", aliases: ["empanada"], category: "prepared", kcal: 210, p: 6, c: 28, f: 8, servingLabel: "1 unidad", servingGrams: 80 },
  { id: "wrap-pollo", name: "Wrap de pollo", aliases: ["wrap"], category: "prepared", kcal: 210, p: 16, c: 22, f: 6, servingLabel: "1 unidad", servingGrams: 180 },
  { id: "ensalada-atun", name: "Ensalada de atún", aliases: ["atun ensalada"], category: "prepared", kcal: 130, p: 16, c: 4, f: 5, servingLabel: "1 bowl", servingGrams: 220 },
  { id: "poke", name: "Poke bowl", aliases: ["poke"], category: "prepared", kcal: 150, p: 12, c: 18, f: 4, servingLabel: "1 bowl", servingGrams: 350 },
  { id: "bowl-quinoa", name: "Bowl de quinoa", aliases: ["quinoa bowl"], category: "prepared", kcal: 140, p: 7, c: 20, f: 4, servingLabel: "1 bowl", servingGrams: 300 },
  { id: "arroz-primavera", name: "Arroz primavera", aliases: ["arroz vegetales"], category: "prepared", kcal: 130, p: 3, c: 24, f: 2.5, servingLabel: "1 plato", servingGrams: 250 },
  { id: "sopa-verdura", name: "Sopa de verduras", aliases: ["sopa"], category: "prepared", kcal: 35, p: 1.5, c: 6, f: 0.5, servingLabel: "1 plato", servingGrams: 300 },
  { id: "caldo", name: "Caldo", aliases: ["consomé"], category: "prepared", kcal: 12, p: 1, c: 1, f: 0.4, servingLabel: "1 taza", servingGrams: 240 },
  { id: "gelatina", name: "Gelatina light", aliases: ["gelatina"], category: "prepared", kcal: 20, p: 1.5, c: 4, f: 0, servingLabel: "1 pote", servingGrams: 120 },
  { id: "flan", name: "Flan", aliases: ["flan"], category: "prepared", kcal: 147, p: 5, c: 23, f: 4, servingLabel: "1 porción", servingGrams: 120 },
  { id: "arroz-leche", name: "Arroz con leche", aliases: ["arroz con leche"], category: "prepared", kcal: 118, p: 3.2, c: 22, f: 2, servingLabel: "1 pote", servingGrams: 150 },
  { id: "budin", name: "Budín", aliases: ["plumcake"], category: "prepared", kcal: 350, p: 6, c: 50, f: 14, servingLabel: "1 feta", servingGrams: 60 },
  { id: "medialuna-grasa", name: "Medialuna de grasa", aliases: ["factura grasa"], category: "prepared", kcal: 360, p: 8, c: 52, f: 13, servingLabel: "1 unidad", servingGrams: 50 },

  { id: "galletitas-arroz-chocolate", name: "Galletas de arroz con chocolate", aliases: ["rice cake chocolate"], category: "packaged", kcal: 450, p: 7, c: 72, f: 14, servingLabel: "1 unidad", servingGrams: 13 },
  { id: "barra-proteina", name: "Barra de proteína", aliases: ["protein bar"], category: "packaged", kcal: 360, p: 30, c: 30, f: 12, servingLabel: "1 unidad", servingGrams: 60 },
  { id: "gelatina-proteica", name: "Gelatina proteica", aliases: ["gelatina prote"], category: "packaged", kcal: 80, p: 18, c: 2, f: 0, servingLabel: "1 pote", servingGrams: 120 },
  { id: "salsa-soja", name: "Salsa de soja", aliases: ["soy sauce"], category: "packaged", kcal: 53, p: 8, c: 5, f: 0, servingLabel: "1 cda", servingGrams: 15 },
  { id: "chimichurri", name: "Chimichurri", aliases: ["chimi"], category: "packaged", kcal: 180, p: 1, c: 4, f: 18, servingLabel: "1 cda", servingGrams: 15 },
  { id: "vinagre", name: "Vinagre", aliases: ["aceto"], category: "packaged", kcal: 18, p: 0, c: 0.9, f: 0, servingLabel: "1 cda", servingGrams: 15 },
  { id: "dulce-batata", name: "Dulce de batata", aliases: ["batata"], category: "packaged", kcal: 240, p: 0.5, c: 60, f: 0.1, servingLabel: "1 feta", servingGrams: 40 },
  { id: "membrillo", name: "Dulce de membrillo", aliases: ["membrillo"], category: "packaged", kcal: 220, p: 0.4, c: 55, f: 0.1, servingLabel: "1 feta", servingGrams: 40 },
  { id: "nachos", name: "Nachos", aliases: ["nacho", "tortilla chips"], category: "packaged", kcal: 489, p: 8, c: 63, f: 24, servingLabel: "1 puñado", servingGrams: 30 },

  { id: "cafe-leche", name: "Café con leche", aliases: ["latte"], category: "drink", kcal: 42, p: 2.2, c: 4, f: 1.8, servingLabel: "1 taza", servingGrams: 200 },
  { id: "capuccino", name: "Cappuccino", aliases: ["capuccino"], category: "drink", kcal: 37, p: 2, c: 3, f: 1.5, servingLabel: "1 taza", servingGrams: 180 },
  { id: "jugo-manzana", name: "Jugo de manzana", aliases: ["apple juice"], category: "drink", kcal: 46, p: 0.1, c: 11, f: 0.1, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "agua-saborizada", name: "Agua saborizada", aliases: ["villa del sur", "levite"], category: "drink", kcal: 18, p: 0, c: 4.5, f: 0, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "isotonic", name: "Bebida isotónica", aliases: ["gatorade", "powerade"], category: "drink", kcal: 24, p: 0, c: 6, f: 0, servingLabel: "1 vaso", servingGrams: 200 },
  { id: "smoothie-proteico", name: "Smoothie proteico", aliases: ["shake"], category: "drink", kcal: 95, p: 12, c: 8, f: 1.5, servingLabel: "1 vaso", servingGrams: 300 },
  { id: "vino-blanco", name: "Vino blanco", aliases: ["chardonnay"], category: "drink", kcal: 82, p: 0.1, c: 2.6, f: 0, servingLabel: "1 copa", servingGrams: 150 },
];
